### ISSUE TITLE
Connecting to a Socket from embassy-net 0.2.1

### ISSUE THREAD

**Issue by Standaa** [obabec/rust-mqtt#30]
Hello,
I am getting an error passing the socket to the Mqtt client.
My code is as follows:

```
    use embassy_net::{
        tcp::TcpSocket,
        {dns::DnsQueryType, Stack},
    };
    use rust_mqtt::{
        client::{client::MqttClient, client_config::ClientConfig},
        utils::rng_generator::CountingRng,
    };
    [...]
    let mut socket = TcpSocket::new(stack, &mut rx_buffer, &mut tx_buffer);
    socket.set_timeout(Some(embassy_time::Duration::from_secs(10)));

     let mut client =
            MqttClient::<_, 5, _>::new(socket, &mut write_buffer, 80, &mut recv_buffer, 80, config);
```

The client initialization is throwing an error: ` the trait embedded_io::asynch::Write is not implemented for TcpSocket<'_>`
How should I work around this error ?

Thanks!

**Comment by lulf** [comment]
Most likely either you need to enable 'nightly' and 'unstable-traits' on embassy-net, or you're using a 'too new' version of embassy-net. A PR was just merged to support newer versions of embedded-io, so I suggest trying with the latest changes on the main branch to see if that helps.
